// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i40;

import 'package:bloc/bloc.dart' as _i58;
import 'package:dartz/dartz.dart' as _i4;
import 'package:ditonton/common/failure.dart' as _i51;
import 'package:ditonton/data/datasources/db/database_helper.dart' as _i39;
import 'package:ditonton/data/datasources/movie_local_data_source.dart' as _i50;
import 'package:ditonton/data/datasources/movie_remote_data_source.dart'
    as _i48;
import 'package:ditonton/data/datasources/tv_local_data_source.dart' as _i46;
import 'package:ditonton/data/datasources/tv_remote_data_source.dart' as _i44;
import 'package:ditonton/data/models/movie_detail_model.dart' as _i3;
import 'package:ditonton/data/models/movie_model.dart' as _i49;
import 'package:ditonton/data/models/movie_table.dart' as _i42;
import 'package:ditonton/data/models/tv_detail_model.dart' as _i2;
import 'package:ditonton/data/models/tv_model.dart' as _i45;
import 'package:ditonton/data/models/tv_table.dart' as _i43;
import 'package:ditonton/domain/entities/movie.dart' as _i54;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i55;
import 'package:ditonton/domain/entities/tv.dart' as _i52;
import 'package:ditonton/domain/entities/tv_detail.dart' as _i53;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i5;
import 'package:ditonton/domain/repositories/tv_repository.dart' as _i6;
import 'package:ditonton/domain/usecases/get_movie_detail.dart' as _i7;
import 'package:ditonton/domain/usecases/get_movie_recommendations.dart' as _i8;
import 'package:ditonton/domain/usecases/get_now_playing_movies.dart' as _i13;
import 'package:ditonton/domain/usecases/get_now_playing_tv.dart' as _i31;
import 'package:ditonton/domain/usecases/get_popular_movies.dart' as _i14;
import 'package:ditonton/domain/usecases/get_popular_tv.dart' as _i20;
import 'package:ditonton/domain/usecases/get_top_rated_movies.dart' as _i15;
import 'package:ditonton/domain/usecases/get_top_rated_tv.dart' as _i23;
import 'package:ditonton/domain/usecases/get_tv_detail.dart' as _i25;
import 'package:ditonton/domain/usecases/get_tv_recommendations.dart' as _i26;
import 'package:ditonton/domain/usecases/get_watchlist_movies.dart' as _i35;
import 'package:ditonton/domain/usecases/get_watchlist_status.dart' as _i9;
import 'package:ditonton/domain/usecases/get_watchlist_status_tv.dart' as _i27;
import 'package:ditonton/domain/usecases/get_watchlist_tv.dart' as _i37;
import 'package:ditonton/domain/usecases/remove_watchlist.dart' as _i11;
import 'package:ditonton/domain/usecases/remove_watchlist_tv.dart' as _i29;
import 'package:ditonton/domain/usecases/save_watchlist.dart' as _i10;
import 'package:ditonton/domain/usecases/save_watchlist_tv.dart' as _i28;
import 'package:ditonton/domain/usecases/search_movies.dart' as _i17;
import 'package:ditonton/domain/usecases/search_tv.dart' as _i33;
import 'package:ditonton/presentation/blocs/movie_detail/movie_detail_bloc.dart'
    as _i56;
import 'package:ditonton/presentation/blocs/movie_detail/movie_detail_event.dart'
    as _i57;
import 'package:ditonton/presentation/blocs/movie_detail/movie_detail_state.dart'
    as _i12;
import 'package:ditonton/presentation/blocs/movie_list/movie_list_bloc.dart'
    as _i16;
import 'package:ditonton/presentation/blocs/movie_search/movie_search_bloc.dart'
    as _i18;
import 'package:ditonton/presentation/blocs/popular_movies/popular_movies_bloc.dart'
    as _i19;
import 'package:ditonton/presentation/blocs/popular_tv/popular_tv_bloc.dart'
    as _i21;
import 'package:ditonton/presentation/blocs/top_rated_movies/top_rated_movies_bloc.dart'
    as _i22;
import 'package:ditonton/presentation/blocs/top_rated_tv/top_rated_tv_bloc.dart'
    as _i24;
import 'package:ditonton/presentation/blocs/tv_detail/tv_detail_bloc.dart'
    as _i30;
import 'package:ditonton/presentation/blocs/tv_list/tv_list_bloc.dart' as _i32;
import 'package:ditonton/presentation/blocs/tv_search/tv_search_bloc.dart'
    as _i34;
import 'package:ditonton/presentation/blocs/watchlist_movie/watchlist_movie_bloc.dart'
    as _i36;
import 'package:ditonton/presentation/blocs/watchlist_tv/watchlist_tv_bloc.dart'
    as _i38;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i47;
import 'package:sqflite/sqflite.dart' as _i41;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvDetailModel_0 extends _i1.SmartFake implements _i2.TvDetailModel {
  _FakeTvDetailModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieRepository_3 extends _i1.SmartFake
    implements _i5.MovieRepository {
  _FakeMovieRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvRepository_4 extends _i1.SmartFake implements _i6.TvRepository {
  _FakeTvRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetMovieDetail_5 extends _i1.SmartFake
    implements _i7.GetMovieDetail {
  _FakeGetMovieDetail_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetMovieRecommendations_6 extends _i1.SmartFake
    implements _i8.GetMovieRecommendations {
  _FakeGetMovieRecommendations_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchListStatus_7 extends _i1.SmartFake
    implements _i9.GetWatchListStatus {
  _FakeGetWatchListStatus_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlist_8 extends _i1.SmartFake implements _i10.SaveWatchlist {
  _FakeSaveWatchlist_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlist_9 extends _i1.SmartFake
    implements _i11.RemoveWatchlist {
  _FakeRemoveWatchlist_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailState_10 extends _i1.SmartFake
    implements _i12.MovieDetailState {
  _FakeMovieDetailState_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetNowPlayingMovies_11 extends _i1.SmartFake
    implements _i13.GetNowPlayingMovies {
  _FakeGetNowPlayingMovies_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularMovies_12 extends _i1.SmartFake
    implements _i14.GetPopularMovies {
  _FakeGetPopularMovies_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedMovies_13 extends _i1.SmartFake
    implements _i15.GetTopRatedMovies {
  _FakeGetTopRatedMovies_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieListState_14 extends _i1.SmartFake
    implements _i16.MovieListState {
  _FakeMovieListState_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchMovies_15 extends _i1.SmartFake implements _i17.SearchMovies {
  _FakeSearchMovies_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieSearchState_16 extends _i1.SmartFake
    implements _i18.MovieSearchState {
  _FakeMovieSearchState_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePopularMoviesState_17 extends _i1.SmartFake
    implements _i19.PopularMoviesState {
  _FakePopularMoviesState_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTv_18 extends _i1.SmartFake implements _i20.GetPopularTv {
  _FakeGetPopularTv_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePopularTvState_19 extends _i1.SmartFake
    implements _i21.PopularTvState {
  _FakePopularTvState_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopRatedMoviesState_20 extends _i1.SmartFake
    implements _i22.TopRatedMoviesState {
  _FakeTopRatedMoviesState_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTv_21 extends _i1.SmartFake
    implements _i23.GetTopRatedTv {
  _FakeGetTopRatedTv_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopRatedTvState_22 extends _i1.SmartFake
    implements _i24.TopRatedTvState {
  _FakeTopRatedTvState_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTvDetail_23 extends _i1.SmartFake implements _i25.GetTvDetail {
  _FakeGetTvDetail_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTvRecommendations_24 extends _i1.SmartFake
    implements _i26.GetTvRecommendations {
  _FakeGetTvRecommendations_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistStatusTv_25 extends _i1.SmartFake
    implements _i27.GetWatchlistStatusTv {
  _FakeGetWatchlistStatusTv_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTv_26 extends _i1.SmartFake
    implements _i28.SaveWatchlistTv {
  _FakeSaveWatchlistTv_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTv_27 extends _i1.SmartFake
    implements _i29.RemoveWatchlistTv {
  _FakeRemoveWatchlistTv_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvDetailState_28 extends _i1.SmartFake
    implements _i30.TvDetailState {
  _FakeTvDetailState_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetNowPlayingTv_29 extends _i1.SmartFake
    implements _i31.GetNowPlayingTv {
  _FakeGetNowPlayingTv_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvListState_30 extends _i1.SmartFake implements _i32.TvListState {
  _FakeTvListState_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchTv_31 extends _i1.SmartFake implements _i33.SearchTv {
  _FakeSearchTv_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSearchState_32 extends _i1.SmartFake
    implements _i34.TvSearchState {
  _FakeTvSearchState_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistMovies_33 extends _i1.SmartFake
    implements _i35.GetWatchlistMovies {
  _FakeGetWatchlistMovies_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWatchlistMovieState_34 extends _i1.SmartFake
    implements _i36.WatchlistMovieState {
  _FakeWatchlistMovieState_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistTv_35 extends _i1.SmartFake
    implements _i37.GetWatchlistTv {
  _FakeGetWatchlistTv_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWatchlistTvState_36 extends _i1.SmartFake
    implements _i38.WatchlistTvState {
  _FakeWatchlistTvState_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i39.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i40.Future<_i41.Database?> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i40.Future<_i41.Database?>.value(),
          )
          as _i40.Future<_i41.Database?>);

  @override
  _i40.Future<int> insertWatchlist(_i42.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i40.Future<int>.value(0),
          )
          as _i40.Future<int>);

  @override
  _i40.Future<int> removeWatchlist(_i42.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i40.Future<int>.value(0),
          )
          as _i40.Future<int>);

  @override
  _i40.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i40.Future<Map<String, dynamic>?>.value(),
          )
          as _i40.Future<Map<String, dynamic>?>);

  @override
  _i40.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i40.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i40.Future<List<Map<String, dynamic>>>);

  @override
  _i40.Future<int> insertTvWatchlist(_i43.TvTable? tv) =>
      (super.noSuchMethod(
            Invocation.method(#insertTvWatchlist, [tv]),
            returnValue: _i40.Future<int>.value(0),
          )
          as _i40.Future<int>);

  @override
  _i40.Future<void> removeTvWatchlist(_i43.TvTable? tv) =>
      (super.noSuchMethod(
            Invocation.method(#removeTvWatchlist, [tv]),
            returnValue: _i40.Future<void>.value(),
            returnValueForMissingStub: _i40.Future<void>.value(),
          )
          as _i40.Future<void>);

  @override
  _i40.Future<Map<String, dynamic>?> getTvById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvById, [id]),
            returnValue: _i40.Future<Map<String, dynamic>?>.value(),
          )
          as _i40.Future<Map<String, dynamic>?>);

  @override
  _i40.Future<List<Map<String, dynamic>>> getTvWatchlist() =>
      (super.noSuchMethod(
            Invocation.method(#getTvWatchlist, []),
            returnValue: _i40.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i40.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i44.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i40.Future<List<_i45.TvModel>> getNowPlayingTv() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingTv, []),
            returnValue: _i40.Future<List<_i45.TvModel>>.value(
              <_i45.TvModel>[],
            ),
          )
          as _i40.Future<List<_i45.TvModel>>);

  @override
  _i40.Future<List<_i45.TvModel>> getPopularTv() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTv, []),
            returnValue: _i40.Future<List<_i45.TvModel>>.value(
              <_i45.TvModel>[],
            ),
          )
          as _i40.Future<List<_i45.TvModel>>);

  @override
  _i40.Future<List<_i45.TvModel>> getTopRatedTv() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTv, []),
            returnValue: _i40.Future<List<_i45.TvModel>>.value(
              <_i45.TvModel>[],
            ),
          )
          as _i40.Future<List<_i45.TvModel>>);

  @override
  _i40.Future<_i2.TvDetailModel> getTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetail, [id]),
            returnValue: _i40.Future<_i2.TvDetailModel>.value(
              _FakeTvDetailModel_0(this, Invocation.method(#getTvDetail, [id])),
            ),
          )
          as _i40.Future<_i2.TvDetailModel>);

  @override
  _i40.Future<List<_i45.TvModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvRecommendations, [id]),
            returnValue: _i40.Future<List<_i45.TvModel>>.value(
              <_i45.TvModel>[],
            ),
          )
          as _i40.Future<List<_i45.TvModel>>);

  @override
  _i40.Future<List<_i45.TvModel>> searchTv(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTv, [query]),
            returnValue: _i40.Future<List<_i45.TvModel>>.value(
              <_i45.TvModel>[],
            ),
          )
          as _i40.Future<List<_i45.TvModel>>);
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i46.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i40.Future<String> insertWatchlist(_i43.TvTable? tv) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [tv]),
            returnValue: _i40.Future<String>.value(
              _i47.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [tv]),
              ),
            ),
          )
          as _i40.Future<String>);

  @override
  _i40.Future<String> removeWatchlist(_i43.TvTable? tv) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tv]),
            returnValue: _i40.Future<String>.value(
              _i47.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [tv]),
              ),
            ),
          )
          as _i40.Future<String>);

  @override
  _i40.Future<_i43.TvTable?> getTvById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvById, [id]),
            returnValue: _i40.Future<_i43.TvTable?>.value(),
          )
          as _i40.Future<_i43.TvTable?>);

  @override
  _i40.Future<List<_i43.TvTable>> getWatchlistTv() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTv, []),
            returnValue: _i40.Future<List<_i43.TvTable>>.value(
              <_i43.TvTable>[],
            ),
          )
          as _i40.Future<List<_i43.TvTable>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i48.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i40.Future<List<_i49.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue: _i40.Future<List<_i49.MovieModel>>.value(
              <_i49.MovieModel>[],
            ),
          )
          as _i40.Future<List<_i49.MovieModel>>);

  @override
  _i40.Future<List<_i49.MovieModel>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i40.Future<List<_i49.MovieModel>>.value(
              <_i49.MovieModel>[],
            ),
          )
          as _i40.Future<List<_i49.MovieModel>>);

  @override
  _i40.Future<List<_i49.MovieModel>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue: _i40.Future<List<_i49.MovieModel>>.value(
              <_i49.MovieModel>[],
            ),
          )
          as _i40.Future<List<_i49.MovieModel>>);

  @override
  _i40.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue: _i40.Future<_i3.MovieDetailResponse>.value(
              _FakeMovieDetailResponse_1(
                this,
                Invocation.method(#getMovieDetail, [id]),
              ),
            ),
          )
          as _i40.Future<_i3.MovieDetailResponse>);

  @override
  _i40.Future<List<_i49.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue: _i40.Future<List<_i49.MovieModel>>.value(
              <_i49.MovieModel>[],
            ),
          )
          as _i40.Future<List<_i49.MovieModel>>);

  @override
  _i40.Future<List<_i49.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue: _i40.Future<List<_i49.MovieModel>>.value(
              <_i49.MovieModel>[],
            ),
          )
          as _i40.Future<List<_i49.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i50.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i40.Future<String> insertWatchlist(_i42.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i40.Future<String>.value(
              _i47.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [movie]),
              ),
            ),
          )
          as _i40.Future<String>);

  @override
  _i40.Future<String> removeWatchlist(_i42.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i40.Future<String>.value(
              _i47.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i40.Future<String>);

  @override
  _i40.Future<_i42.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i40.Future<_i42.MovieTable?>.value(),
          )
          as _i40.Future<_i42.MovieTable?>);

  @override
  _i40.Future<List<_i42.MovieTable>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i40.Future<List<_i42.MovieTable>>.value(
              <_i42.MovieTable>[],
            ),
          )
          as _i40.Future<List<_i42.MovieTable>>);
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i6.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>> getNowPlayingTv() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingTv, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i52.Tv>>(
                    this,
                    Invocation.method(#getNowPlayingTv, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>> getPopularTv() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTv, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i52.Tv>>(
                    this,
                    Invocation.method(#getPopularTv, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>> getTopRatedTv() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTv, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i52.Tv>>(
                    this,
                    Invocation.method(#getTopRatedTv, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, _i53.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvDetail, [id]),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, _i53.TvDetail>>.value(
                  _FakeEither_2<_i51.Failure, _i53.TvDetail>(
                    this,
                    Invocation.method(#getTvDetail, [id]),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, _i53.TvDetail>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>> getTvRecommendations(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTvRecommendations, [id]),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i52.Tv>>(
                    this,
                    Invocation.method(#getTvRecommendations, [id]),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>> searchTv(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTv, [query]),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i52.Tv>>(
                    this,
                    Invocation.method(#searchTv, [query]),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, String>> saveWatchlist(
    _i53.TvDetail? tv,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [tv]),
            returnValue: _i40.Future<_i4.Either<_i51.Failure, String>>.value(
              _FakeEither_2<_i51.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [tv]),
              ),
            ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, String>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, String>> removeWatchlist(
    _i53.TvDetail? tv,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tv]),
            returnValue: _i40.Future<_i4.Either<_i51.Failure, String>>.value(
              _FakeEither_2<_i51.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [tv]),
              ),
            ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, String>>);

  @override
  _i40.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i40.Future<bool>.value(false),
          )
          as _i40.Future<bool>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>> getWatchlistTv() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTv, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i52.Tv>>(
                    this,
                    Invocation.method(#getWatchlistTv, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i5.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>
  getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i54.Movie>>(
                    this,
                    Invocation.method(#getNowPlayingMovies, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i54.Movie>>(
                    this,
                    Invocation.method(#getPopularMovies, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i54.Movie>>(
                    this,
                    Invocation.method(#getTopRatedMovies, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, _i55.MovieDetail>> getMovieDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, _i55.MovieDetail>>.value(
                  _FakeEither_2<_i51.Failure, _i55.MovieDetail>(
                    this,
                    Invocation.method(#getMovieDetail, [id]),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, _i55.MovieDetail>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>
  getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i54.Movie>>(
                    this,
                    Invocation.method(#getMovieRecommendations, [id]),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>> searchMovies(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i54.Movie>>(
                    this,
                    Invocation.method(#searchMovies, [query]),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, String>> saveWatchlist(
    _i55.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [movie]),
            returnValue: _i40.Future<_i4.Either<_i51.Failure, String>>.value(
              _FakeEither_2<_i51.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [movie]),
              ),
            ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, String>>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, String>> removeWatchlist(
    _i55.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i40.Future<_i4.Either<_i51.Failure, String>>.value(
              _FakeEither_2<_i51.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, String>>);

  @override
  _i40.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i40.Future<bool>.value(false),
          )
          as _i40.Future<bool>);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>
  getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i54.Movie>>(
                    this,
                    Invocation.method(#getWatchlistMovies, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>);
}

/// A class which mocks [GetNowPlayingMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNowPlayingMovies extends _i1.Mock
    implements _i13.GetNowPlayingMovies {
  MockGetNowPlayingMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.MovieRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i54.Movie>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>);
}

/// A class which mocks [GetPopularMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularMovies extends _i1.Mock implements _i14.GetPopularMovies {
  MockGetPopularMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.MovieRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i54.Movie>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>);
}

/// A class which mocks [GetTopRatedMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedMovies extends _i1.Mock implements _i15.GetTopRatedMovies {
  MockGetTopRatedMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.MovieRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i54.Movie>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>);
}

/// A class which mocks [GetMovieDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieDetail extends _i1.Mock implements _i7.GetMovieDetail {
  MockGetMovieDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.MovieRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, _i55.MovieDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, _i55.MovieDetail>>.value(
                  _FakeEither_2<_i51.Failure, _i55.MovieDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, _i55.MovieDetail>>);
}

/// A class which mocks [GetMovieRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieRecommendations extends _i1.Mock
    implements _i8.GetMovieRecommendations {
  MockGetMovieRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.MovieRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>> execute(dynamic id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i54.Movie>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>);
}

/// A class which mocks [SaveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlist extends _i1.Mock implements _i10.SaveWatchlist {
  MockSaveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.MovieRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, String>> execute(
    _i55.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [movie]),
            returnValue: _i40.Future<_i4.Either<_i51.Failure, String>>.value(
              _FakeEither_2<_i51.Failure, String>(
                this,
                Invocation.method(#execute, [movie]),
              ),
            ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, String>>);
}

/// A class which mocks [RemoveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlist extends _i1.Mock implements _i11.RemoveWatchlist {
  MockRemoveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.MovieRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, String>> execute(
    _i55.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [movie]),
            returnValue: _i40.Future<_i4.Either<_i51.Failure, String>>.value(
              _FakeEither_2<_i51.Failure, String>(
                this,
                Invocation.method(#execute, [movie]),
              ),
            ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, String>>);
}

/// A class which mocks [GetWatchListStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatus extends _i1.Mock
    implements _i9.GetWatchListStatus {
  MockGetWatchListStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.MovieRepository);

  @override
  _i40.Future<bool> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i40.Future<bool>.value(false),
          )
          as _i40.Future<bool>);
}

/// A class which mocks [GetWatchlistMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistMovies extends _i1.Mock
    implements _i35.GetWatchlistMovies {
  MockGetWatchlistMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i54.Movie>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>);
}

/// A class which mocks [SearchMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchMovies extends _i1.Mock implements _i17.SearchMovies {
  MockSearchMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.MovieRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>> execute(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query]),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i54.Movie>>(
                    this,
                    Invocation.method(#execute, [query]),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i54.Movie>>>);
}

/// A class which mocks [GetNowPlayingTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNowPlayingTv extends _i1.Mock implements _i31.GetNowPlayingTv {
  MockGetNowPlayingTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.TvRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i52.Tv>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>);
}

/// A class which mocks [GetPopularTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTv extends _i1.Mock implements _i20.GetPopularTv {
  MockGetPopularTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.TvRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i52.Tv>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>);
}

/// A class which mocks [GetTopRatedTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTv extends _i1.Mock implements _i23.GetTopRatedTv {
  MockGetTopRatedTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.TvRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i52.Tv>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>);
}

/// A class which mocks [GetTvDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvDetail extends _i1.Mock implements _i25.GetTvDetail {
  MockGetTvDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.TvRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, _i53.TvDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, _i53.TvDetail>>.value(
                  _FakeEither_2<_i51.Failure, _i53.TvDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, _i53.TvDetail>>);
}

/// A class which mocks [GetTvRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvRecommendations extends _i1.Mock
    implements _i26.GetTvRecommendations {
  MockGetTvRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.TvRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>> execute(dynamic id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i52.Tv>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>);
}

/// A class which mocks [SaveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTv extends _i1.Mock implements _i28.SaveWatchlistTv {
  MockSaveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.TvRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, String>> execute(_i53.TvDetail? tv) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tv]),
            returnValue: _i40.Future<_i4.Either<_i51.Failure, String>>.value(
              _FakeEither_2<_i51.Failure, String>(
                this,
                Invocation.method(#execute, [tv]),
              ),
            ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTv extends _i1.Mock implements _i29.RemoveWatchlistTv {
  MockRemoveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.TvRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, String>> execute(_i53.TvDetail? tv) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tv]),
            returnValue: _i40.Future<_i4.Either<_i51.Failure, String>>.value(
              _FakeEither_2<_i51.Failure, String>(
                this,
                Invocation.method(#execute, [tv]),
              ),
            ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, String>>);
}

/// A class which mocks [GetWatchlistStatusTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistStatusTv extends _i1.Mock
    implements _i27.GetWatchlistStatusTv {
  MockGetWatchlistStatusTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.TvRepository);

  @override
  _i40.Future<bool> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i40.Future<bool>.value(false),
          )
          as _i40.Future<bool>);
}

/// A class which mocks [SearchTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTv extends _i1.Mock implements _i33.SearchTv {
  MockSearchTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.TvRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>> execute(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query]),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i52.Tv>>(
                    this,
                    Invocation.method(#execute, [query]),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>);
}

/// A class which mocks [GetWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTv extends _i1.Mock implements _i37.GetWatchlistTv {
  MockGetWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvRepository_4(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i6.TvRepository);

  @override
  _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>.value(
                  _FakeEither_2<_i51.Failure, List<_i52.Tv>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i40.Future<_i4.Either<_i51.Failure, List<_i52.Tv>>>);
}

/// A class which mocks [MovieDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailBloc extends _i1.Mock implements _i56.MovieDetailBloc {
  MockMovieDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.GetMovieDetail get getMovieDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getMovieDetail),
            returnValue: _FakeGetMovieDetail_5(
              this,
              Invocation.getter(#getMovieDetail),
            ),
          )
          as _i7.GetMovieDetail);

  @override
  _i8.GetMovieRecommendations get getMovieRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getMovieRecommendations),
            returnValue: _FakeGetMovieRecommendations_6(
              this,
              Invocation.getter(#getMovieRecommendations),
            ),
          )
          as _i8.GetMovieRecommendations);

  @override
  _i9.GetWatchListStatus get getWatchListStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchListStatus),
            returnValue: _FakeGetWatchListStatus_7(
              this,
              Invocation.getter(#getWatchListStatus),
            ),
          )
          as _i9.GetWatchListStatus);

  @override
  _i10.SaveWatchlist get saveWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlist),
            returnValue: _FakeSaveWatchlist_8(
              this,
              Invocation.getter(#saveWatchlist),
            ),
          )
          as _i10.SaveWatchlist);

  @override
  _i11.RemoveWatchlist get removeWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlist),
            returnValue: _FakeRemoveWatchlist_9(
              this,
              Invocation.getter(#removeWatchlist),
            ),
          )
          as _i11.RemoveWatchlist);

  @override
  _i12.MovieDetailState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieDetailState_10(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i12.MovieDetailState);

  @override
  _i40.Stream<_i12.MovieDetailState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i40.Stream<_i12.MovieDetailState>.empty(),
          )
          as _i40.Stream<_i12.MovieDetailState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i57.MovieDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i57.MovieDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i12.MovieDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i57.MovieDetailEvent>(
    _i58.EventHandler<E, _i12.MovieDetailState>? handler, {
    _i58.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i58.Transition<_i57.MovieDetailEvent, _i12.MovieDetailState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i40.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i40.Future<void>.value(),
            returnValueForMissingStub: _i40.Future<void>.value(),
          )
          as _i40.Future<void>);

  @override
  void onChange(_i58.Change<_i12.MovieDetailState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MovieListBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieListBloc extends _i1.Mock implements _i16.MovieListBloc {
  MockMovieListBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.GetNowPlayingMovies get getNowPlayingMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getNowPlayingMovies),
            returnValue: _FakeGetNowPlayingMovies_11(
              this,
              Invocation.getter(#getNowPlayingMovies),
            ),
          )
          as _i13.GetNowPlayingMovies);

  @override
  _i14.GetPopularMovies get getPopularMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularMovies),
            returnValue: _FakeGetPopularMovies_12(
              this,
              Invocation.getter(#getPopularMovies),
            ),
          )
          as _i14.GetPopularMovies);

  @override
  _i15.GetTopRatedMovies get getTopRatedMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedMovies),
            returnValue: _FakeGetTopRatedMovies_13(
              this,
              Invocation.getter(#getTopRatedMovies),
            ),
          )
          as _i15.GetTopRatedMovies);

  @override
  _i16.MovieListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieListState_14(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i16.MovieListState);

  @override
  _i40.Stream<_i16.MovieListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i40.Stream<_i16.MovieListState>.empty(),
          )
          as _i40.Stream<_i16.MovieListState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i16.MovieListEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i16.MovieListEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i16.MovieListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i16.MovieListEvent>(
    _i58.EventHandler<E, _i16.MovieListState>? handler, {
    _i58.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i58.Transition<_i16.MovieListEvent, _i16.MovieListState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i40.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i40.Future<void>.value(),
            returnValueForMissingStub: _i40.Future<void>.value(),
          )
          as _i40.Future<void>);

  @override
  void onChange(_i58.Change<_i16.MovieListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MovieSearchBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieSearchBloc extends _i1.Mock implements _i18.MovieSearchBloc {
  MockMovieSearchBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i17.SearchMovies get searchMovies =>
      (super.noSuchMethod(
            Invocation.getter(#searchMovies),
            returnValue: _FakeSearchMovies_15(
              this,
              Invocation.getter(#searchMovies),
            ),
          )
          as _i17.SearchMovies);

  @override
  _i18.MovieSearchState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieSearchState_16(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i18.MovieSearchState);

  @override
  _i40.Stream<_i18.MovieSearchState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i40.Stream<_i18.MovieSearchState>.empty(),
          )
          as _i40.Stream<_i18.MovieSearchState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i18.MovieSearchEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i18.MovieSearchEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i18.MovieSearchState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i18.MovieSearchEvent>(
    _i58.EventHandler<E, _i18.MovieSearchState>? handler, {
    _i58.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i58.Transition<_i18.MovieSearchEvent, _i18.MovieSearchState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i40.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i40.Future<void>.value(),
            returnValueForMissingStub: _i40.Future<void>.value(),
          )
          as _i40.Future<void>);

  @override
  void onChange(_i58.Change<_i18.MovieSearchState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PopularMoviesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularMoviesBloc extends _i1.Mock implements _i19.PopularMoviesBloc {
  MockPopularMoviesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.GetPopularMovies get getPopularMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularMovies),
            returnValue: _FakeGetPopularMovies_12(
              this,
              Invocation.getter(#getPopularMovies),
            ),
          )
          as _i14.GetPopularMovies);

  @override
  _i19.PopularMoviesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePopularMoviesState_17(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i19.PopularMoviesState);

  @override
  _i40.Stream<_i19.PopularMoviesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i40.Stream<_i19.PopularMoviesState>.empty(),
          )
          as _i40.Stream<_i19.PopularMoviesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i19.PopularMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i19.PopularMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i19.PopularMoviesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i19.PopularMoviesEvent>(
    _i58.EventHandler<E, _i19.PopularMoviesState>? handler, {
    _i58.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i58.Transition<_i19.PopularMoviesEvent, _i19.PopularMoviesState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i40.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i40.Future<void>.value(),
            returnValueForMissingStub: _i40.Future<void>.value(),
          )
          as _i40.Future<void>);

  @override
  void onChange(_i58.Change<_i19.PopularMoviesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PopularTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTvBloc extends _i1.Mock implements _i21.PopularTvBloc {
  MockPopularTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.GetPopularTv get getPopularTv =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularTv),
            returnValue: _FakeGetPopularTv_18(
              this,
              Invocation.getter(#getPopularTv),
            ),
          )
          as _i20.GetPopularTv);

  @override
  _i21.PopularTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakePopularTvState_19(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i21.PopularTvState);

  @override
  _i40.Stream<_i21.PopularTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i40.Stream<_i21.PopularTvState>.empty(),
          )
          as _i40.Stream<_i21.PopularTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i21.PopularTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i21.PopularTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i21.PopularTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i21.PopularTvEvent>(
    _i58.EventHandler<E, _i21.PopularTvState>? handler, {
    _i58.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i58.Transition<_i21.PopularTvEvent, _i21.PopularTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i40.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i40.Future<void>.value(),
            returnValueForMissingStub: _i40.Future<void>.value(),
          )
          as _i40.Future<void>);

  @override
  void onChange(_i58.Change<_i21.PopularTvState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedMoviesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedMoviesBloc extends _i1.Mock
    implements _i22.TopRatedMoviesBloc {
  MockTopRatedMoviesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.GetTopRatedMovies get getTopRatedMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedMovies),
            returnValue: _FakeGetTopRatedMovies_13(
              this,
              Invocation.getter(#getTopRatedMovies),
            ),
          )
          as _i15.GetTopRatedMovies);

  @override
  _i22.TopRatedMoviesState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTopRatedMoviesState_20(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i22.TopRatedMoviesState);

  @override
  _i40.Stream<_i22.TopRatedMoviesState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i40.Stream<_i22.TopRatedMoviesState>.empty(),
          )
          as _i40.Stream<_i22.TopRatedMoviesState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i22.TopRatedMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i22.TopRatedMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i22.TopRatedMoviesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i22.TopRatedMoviesEvent>(
    _i58.EventHandler<E, _i22.TopRatedMoviesState>? handler, {
    _i58.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i58.Transition<_i22.TopRatedMoviesEvent, _i22.TopRatedMoviesState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i40.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i40.Future<void>.value(),
            returnValueForMissingStub: _i40.Future<void>.value(),
          )
          as _i40.Future<void>);

  @override
  void onChange(_i58.Change<_i22.TopRatedMoviesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvBloc extends _i1.Mock implements _i24.TopRatedTvBloc {
  MockTopRatedTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.GetTopRatedTv get getTopRatedTv =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTv),
            returnValue: _FakeGetTopRatedTv_21(
              this,
              Invocation.getter(#getTopRatedTv),
            ),
          )
          as _i23.GetTopRatedTv);

  @override
  _i24.TopRatedTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTopRatedTvState_22(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i24.TopRatedTvState);

  @override
  _i40.Stream<_i24.TopRatedTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i40.Stream<_i24.TopRatedTvState>.empty(),
          )
          as _i40.Stream<_i24.TopRatedTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i24.TopRatedTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i24.TopRatedTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i24.TopRatedTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i24.TopRatedTvEvent>(
    _i58.EventHandler<E, _i24.TopRatedTvState>? handler, {
    _i58.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i58.Transition<_i24.TopRatedTvEvent, _i24.TopRatedTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i40.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i40.Future<void>.value(),
            returnValueForMissingStub: _i40.Future<void>.value(),
          )
          as _i40.Future<void>);

  @override
  void onChange(_i58.Change<_i24.TopRatedTvState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TvDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDetailBloc extends _i1.Mock implements _i30.TvDetailBloc {
  MockTvDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i25.GetTvDetail get getTvDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getTvDetail),
            returnValue: _FakeGetTvDetail_23(
              this,
              Invocation.getter(#getTvDetail),
            ),
          )
          as _i25.GetTvDetail);

  @override
  _i26.GetTvRecommendations get getTvRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getTvRecommendations),
            returnValue: _FakeGetTvRecommendations_24(
              this,
              Invocation.getter(#getTvRecommendations),
            ),
          )
          as _i26.GetTvRecommendations);

  @override
  _i27.GetWatchlistStatusTv get getWatchlistStatusTv =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistStatusTv),
            returnValue: _FakeGetWatchlistStatusTv_25(
              this,
              Invocation.getter(#getWatchlistStatusTv),
            ),
          )
          as _i27.GetWatchlistStatusTv);

  @override
  _i28.SaveWatchlistTv get saveWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlist),
            returnValue: _FakeSaveWatchlistTv_26(
              this,
              Invocation.getter(#saveWatchlist),
            ),
          )
          as _i28.SaveWatchlistTv);

  @override
  _i29.RemoveWatchlistTv get removeWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlist),
            returnValue: _FakeRemoveWatchlistTv_27(
              this,
              Invocation.getter(#removeWatchlist),
            ),
          )
          as _i29.RemoveWatchlistTv);

  @override
  _i30.TvDetailState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTvDetailState_28(this, Invocation.getter(#state)),
          )
          as _i30.TvDetailState);

  @override
  _i40.Stream<_i30.TvDetailState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i40.Stream<_i30.TvDetailState>.empty(),
          )
          as _i40.Stream<_i30.TvDetailState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i30.TvDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i30.TvDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i30.TvDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i30.TvDetailEvent>(
    _i58.EventHandler<E, _i30.TvDetailState>? handler, {
    _i58.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i58.Transition<_i30.TvDetailEvent, _i30.TvDetailState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i40.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i40.Future<void>.value(),
            returnValueForMissingStub: _i40.Future<void>.value(),
          )
          as _i40.Future<void>);

  @override
  void onChange(_i58.Change<_i30.TvDetailState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TvListBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvListBloc extends _i1.Mock implements _i32.TvListBloc {
  MockTvListBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i31.GetNowPlayingTv get getNowPlayingTv =>
      (super.noSuchMethod(
            Invocation.getter(#getNowPlayingTv),
            returnValue: _FakeGetNowPlayingTv_29(
              this,
              Invocation.getter(#getNowPlayingTv),
            ),
          )
          as _i31.GetNowPlayingTv);

  @override
  _i20.GetPopularTv get getPopularTv =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularTv),
            returnValue: _FakeGetPopularTv_18(
              this,
              Invocation.getter(#getPopularTv),
            ),
          )
          as _i20.GetPopularTv);

  @override
  _i23.GetTopRatedTv get getTopRatedTv =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTv),
            returnValue: _FakeGetTopRatedTv_21(
              this,
              Invocation.getter(#getTopRatedTv),
            ),
          )
          as _i23.GetTopRatedTv);

  @override
  _i32.TvListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTvListState_30(this, Invocation.getter(#state)),
          )
          as _i32.TvListState);

  @override
  _i40.Stream<_i32.TvListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i40.Stream<_i32.TvListState>.empty(),
          )
          as _i40.Stream<_i32.TvListState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i32.TvListEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i32.TvListEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i32.TvListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i32.TvListEvent>(
    _i58.EventHandler<E, _i32.TvListState>? handler, {
    _i58.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i58.Transition<_i32.TvListEvent, _i32.TvListState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i40.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i40.Future<void>.value(),
            returnValueForMissingStub: _i40.Future<void>.value(),
          )
          as _i40.Future<void>);

  @override
  void onChange(_i58.Change<_i32.TvListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TvSearchBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSearchBloc extends _i1.Mock implements _i34.TvSearchBloc {
  MockTvSearchBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i33.SearchTv get searchTv =>
      (super.noSuchMethod(
            Invocation.getter(#searchTv),
            returnValue: _FakeSearchTv_31(this, Invocation.getter(#searchTv)),
          )
          as _i33.SearchTv);

  @override
  _i34.TvSearchState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTvSearchState_32(this, Invocation.getter(#state)),
          )
          as _i34.TvSearchState);

  @override
  _i40.Stream<_i34.TvSearchState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i40.Stream<_i34.TvSearchState>.empty(),
          )
          as _i40.Stream<_i34.TvSearchState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i34.TvSearchEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i34.TvSearchEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i34.TvSearchState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i34.TvSearchEvent>(
    _i58.EventHandler<E, _i34.TvSearchState>? handler, {
    _i58.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i58.Transition<_i34.TvSearchEvent, _i34.TvSearchState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i40.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i40.Future<void>.value(),
            returnValueForMissingStub: _i40.Future<void>.value(),
          )
          as _i40.Future<void>);

  @override
  void onChange(_i58.Change<_i34.TvSearchState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WatchlistMovieBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistMovieBloc extends _i1.Mock
    implements _i36.WatchlistMovieBloc {
  MockWatchlistMovieBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i35.GetWatchlistMovies get getWatchlistMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistMovies),
            returnValue: _FakeGetWatchlistMovies_33(
              this,
              Invocation.getter(#getWatchlistMovies),
            ),
          )
          as _i35.GetWatchlistMovies);

  @override
  _i36.WatchlistMovieState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeWatchlistMovieState_34(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i36.WatchlistMovieState);

  @override
  _i40.Stream<_i36.WatchlistMovieState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i40.Stream<_i36.WatchlistMovieState>.empty(),
          )
          as _i40.Stream<_i36.WatchlistMovieState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i36.WatchlistMovieEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i36.WatchlistMovieEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i36.WatchlistMovieState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i36.WatchlistMovieEvent>(
    _i58.EventHandler<E, _i36.WatchlistMovieState>? handler, {
    _i58.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i58.Transition<_i36.WatchlistMovieEvent, _i36.WatchlistMovieState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i40.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i40.Future<void>.value(),
            returnValueForMissingStub: _i40.Future<void>.value(),
          )
          as _i40.Future<void>);

  @override
  void onChange(_i58.Change<_i36.WatchlistMovieState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WatchlistTvBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistTvBloc extends _i1.Mock implements _i38.WatchlistTvBloc {
  MockWatchlistTvBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i37.GetWatchlistTv get getWatchlistTv =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchlistTv),
            returnValue: _FakeGetWatchlistTv_35(
              this,
              Invocation.getter(#getWatchlistTv),
            ),
          )
          as _i37.GetWatchlistTv);

  @override
  _i38.WatchlistTvState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeWatchlistTvState_36(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i38.WatchlistTvState);

  @override
  _i40.Stream<_i38.WatchlistTvState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i40.Stream<_i38.WatchlistTvState>.empty(),
          )
          as _i40.Stream<_i38.WatchlistTvState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i38.WatchlistTvEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i38.WatchlistTvEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i38.WatchlistTvState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i38.WatchlistTvEvent>(
    _i58.EventHandler<E, _i38.WatchlistTvState>? handler, {
    _i58.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i58.Transition<_i38.WatchlistTvEvent, _i38.WatchlistTvState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i40.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i40.Future<void>.value(),
            returnValueForMissingStub: _i40.Future<void>.value(),
          )
          as _i40.Future<void>);

  @override
  void onChange(_i58.Change<_i38.WatchlistTvState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
